// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzU-DPxOwktPnUg2kUQAXN2UBqdiScsY',
    appId: '1:782708697467:web:eb5dde1794001a692535de',
    messagingSenderId: '782708697467',
    projectId: 'casus-b1481',
    authDomain: 'casus-b1481.firebaseapp.com',
    storageBucket: 'casus-b1481.firebasestorage.app',
    measurementId: 'G-0LJCYZMMWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOILJ6xuKL4diZvQfCZ6pvEdr2uuiCXE0',
    appId: '1:782708697467:android:90d850b9006376062535de',
    messagingSenderId: '782708697467',
    projectId: 'casus-b1481',
    storageBucket: 'casus-b1481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_6NpvjGvxDZ7l3zXRS7SLGABHuHjAtQw',
    appId: '1:782708697467:ios:0bb57d354670ed4a2535de',
    messagingSenderId: '782708697467',
    projectId: 'casus-b1481',
    storageBucket: 'casus-b1481.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_6NpvjGvxDZ7l3zXRS7SLGABHuHjAtQw',
    appId: '1:782708697467:ios:0bb57d354670ed4a2535de',
    messagingSenderId: '782708697467',
    projectId: 'casus-b1481',
    storageBucket: 'casus-b1481.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzU-DPxOwktPnUg2kUQAXN2UBqdiScsY',
    appId: '1:782708697467:web:19b67f39efe100062535de',
    messagingSenderId: '782708697467',
    projectId: 'casus-b1481',
    authDomain: 'casus-b1481.firebaseapp.com',
    storageBucket: 'casus-b1481.firebasestorage.app',
    measurementId: 'G-L9DLQMYY24',
  );
}
